### ISSUE TITLE
URLscan check is limited

### ISSUE THREAD

**Issue by JoshuaMart** [hueristiq/xurlfind3r#29]
Hi,
As it stands, the URLScan check seems to me to be limited for two reasons :

- It's not possible to specify an API key, so you can quickly get stuck if you scan several URLs.
  - See https://urlscan.io/docs/api/ > "Quotas & Rate Limiting"
- Results extraction seems to be limited to 100 (i.e. the first page). Is necessary to check if the response contains more than 100 results and, if so, iterate to retrieve the other results.
  - See https://urlscan.io/docs/api/ > "Search API"
  - An example : https://github.com/lc/gau/blob/master/pkg/providers/urlscan/urlscan.go
  
  Regards

**Comment by enenumxela** [comment]
On it. Thanks for you contribution. Your issues will be addressed in the next release
