### ISSUE TITLE
config.yaml new loaction

### ISSUE THREAD

**Issue by Hacktus** [hueristiq/xurlfind3r#48]
Hey there, 

config.yaml file is no longer under `$HOME/.hueristiq/xurlfind3r/config.yaml` , it's currently under `/$HOME/.config/xurlfind3r/config.yaml` , please update it in the readme file

**Comment by Hacktus** [comment]
Seems like there is another issue with intel x 

`[ERR] intelx: unexpected status code 400 received from https://2.intelx.io/phonebook/search/result?k=key&id=00000000-0000-0000-0000-000000000000&limit=10000`

in the ID value it doesn't generate an actual search id , instead, it uses `00000000-0000-0000-0000-000000000000` which causes the call to crash

**Comment by enenumxela** [comment]
> Hey there,
> 
> config.yaml file is no longer under `$HOME/.hueristiq/xurlfind3r/config.yaml` , it's currently under `/$HOME/.config/xurlfind3r/config.yaml` , please update it in the readme file

Ooh! yeah!

**Comment by enenumxela** [comment]
Let me check on the issues
